const char* DefaultEncCfg = "\
#########################################################\n\
# Parameters\n\
##########################################################################################\n\
ImageWidth              = 320         # Image width in Pels, must be multiple of 16\n\
ImageHeight             = 128         # Image height in Pels, must be multiple of 16\n\
FrameRate               = 8500        # Frame Rate per second*1000 (1-100)\n\
BitRate                 = 12000       # Bitrate(bps)  #if ZERO=>> RC is OFF\n\
ChromaFormat            = 9           # 9 => XDM_YUV_420P\n\
InterlacedVideo         = 0           # 0 => Progressive, 1 => Interlaced\n\
EnableVUIParam          = 0           # 0 => Disable VUI Parameters, 1 => Enable VUI parameters, 4 => encoded VUI buffer externally provided by Application user, 8 => VUI buffer externally provided as a part of extended dynamic parameters\n\
EnableBufSEI            = 0	        # 1 => Enable Buffering Period SEI Message, 0 => Disable\n\
ME_Type                 = 1           # 0 = Normal Search, 1 = Improved SKip MBs(performance will reduce)\n\
RC_PRESET               = 5           # 1 => Low Delay, 2 => Storage, 3 => 2 Pass, 4 => None, 5 => user defined\n\
ENC_PRESET              = 1           # 0 => default, 1 => High Quality, 2 => High Speed, 3 => user defined\n\
\n\
##########################################################################################\n\
# Encoder Control\n\
##########################################################################################\n\
ProfileIDC              = 77         # Profile IDC (66=baseline, 77=main, 88=extended, 100=HighProfile)\n\
LevelIDC                = 40          # Level IDC   (e.g. 20 = level 2.0)\n\
Log2MaxFrameNumMinus4   = 0           # Sets the maximum frame number (Aloowed values 0 -12)\n\
ConstraintFlag          = 0           # Bit 0 set/reset constraint flag 0, Bit 1 set/reset constraint flag 1,Bit 2 set/reset constraint flag 2,Bit 3 set/reset constraint flag 3\n\
IntraPeriod             = 0           # Period of I-Frames (0 -> only 1st one is I- Frame, 1 -> all I-Frames (range 0 - 255)\n\
IDRFramePeriod          = 90           # Period of IDR Frames (0 -> only 1st one is IDR- Frame, 1 -> all IDR-Frames (range 0 - 255) (IDR overrides I, if both periods match)\n\
LongTermRefreshInterval = 0           # Interval to refresh longterm reference frames.\n\
EnableLongTermFrame     = 0           # 0 -> Disable using longterm reference frame, 1 -> Use longterm frame for reference\n\
FramesToEncode          = 0           # Number of frames to be coded\n\
SliceSize               = 0           # Size of each slice in bits\n\
RateControl             = 1           # 0 => CBR, 1 => VBR, 2 => Fixed QP, 3=> CVBR, 4=> FIXED_RC 5=> CBR custom1 6=> VBR custom1\n\
MaxDelay                = 5000        # Delay Parameter for Rate Control in milliseconds (>=100)\n\
QPInit                  = 51          # Initial QP for RC (-1,0-51)\n\
QPISlice                = 51          # Quant. param for I Slices (0-51)\n\
QPSlice                 = 27          # Quant. param for non - I slices (0-51)\n\
MaxQP                   = 31          # Maximum value for QP (0-51)\n\
MinQP                   = 8           # Minimum value for QP (0-51)\n\
MaxQPI                  = 33          # Maximum value for QP for I frame(0-51)\n\
MinQPI                  = 0           # Minimum value for QP for I frame(0-51)\n\
AirRate                 = 0           # Number of Forced Intra MBs\n\
EntropyCodingMode       = 1           # Entropy Coding Mode (0 = CAVLC, 1 = CABAC)\n\
Transform8x8FlagIntra   = 0           # 0 = Disable, 1 = Enable\n\
Transform8x8FlagInter   = 0           # 0 = Disable, 1 = Enable\n\
SequenceScalingFlag     = 0           # 0 = Disable, 1 = Auto, 2 = Low, 3 = Moderate, 4 = Reserved , 5 = User Defined Scaling Matrices\n\
PerceptualRC            = 1           # 1 => Enable Perceptual QP modulation, 0 => Disable\n\
EncoderQuality          = 2           # 0 => version 1.1 backward compatible mode, 1 => version 1.1 backward compatible Improved Quality mode, 2 => High Quality Platinum mode, 3 => High Speed Platinum mode\n\
mvSADout                = 0           # 0->disable mvsad out, 1->enable mvsad out\n\
useARM926Tcm            = 0           # 0->do not use arm 926 tcm 1-> use arm 926 tcm\n\
enableROI               = 0           # 0->disable ROI 1-> enable ROI\n\
mapIMCOPtoDDR           = 0           # 0->do not use DDR 1-> use DDR instead of IMCOP\n\
metaDataGenerateConsume = 0           # 0->Not in use, 1-> Generate Meta data, 2-> Use Metadata generated by other encoder.\n\
sliceMode               = 0           # 0 -> no multiple slices, 1 -> multiple slices - bits/slice , 2 -> multiple slices-MBs/slice, 3 -> multiple slices - Rows/slice\n\
numTemporalLayers       = 0           # 0-> one layer, 1-> two layer, 2-> three layer, 3-> four layer, 255 -> Chain free P frames\n\
svcSyntaxEnable         = 0           # 0-> SVC off ST refframes, 1-> SVC on ST refframes, 2-> SVC off LT refframes, 3-> SVC on LT refframes,\n\
outputDataMode          = 1           # 0 -> low latency, encoded streams produced after N (configurable) slices encode, 1 -> encoded stream produce at the end of frame\n\
sliceFormat             = 1           # 0-> encoded stream in NAL unit format, 1 -> encoded stream in bytes stream format\n\
interlaceRefMode        = 0           # 0 = ARF (default mode), 1 = SPF, 2 = MRCF\n\
maxBitrateCVBR          = 0 	        # Max bit rate for CVBR RC algortihm\n\
enableGDR               = 0           # Flag to enable Gradual Decoder Refresh\n\
GDRduration             = 4           # GDR refresh duration\n\
GDRinterval             = 100          # Interval between GDR refresh\n\
#########################################################################################\n\
# Loop filter parameters\n\
##########################################################################################\n\
LoopFilterDisable       = 0           # Disable loop filter in slice header (0=Filter, 1=No Filter,\n\
";
